# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44d53cb23e5234ce7baebe8c854cd097df73f7ffa20a9dc665666e28e83da8818321cc0390f08462f22e7c5169a5e51f7fe561bb590b8b8040e60344036abfbb

test:
  secret_key_base: b21c60f0bc34d5771bad76e3685d98eaee6c890377ce59620a0aa220b1f80fe9776e062ac8c58813545cdacb8391e240d22da1ef716f49c29006444e482adb66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
